### ISSUE TITLE
Remove informational log message in FUIFirestoreCollectionViewDataSource.m

### ISSUE THREAD

**Issue by ghowen** [firebase/FirebaseUI-iOS#418]
In FUIFirestoreCollectionViewDataSource.m in line 136-137 the datasource prints the contents of the FUISnapshotArrayDiff to the console. 

    NSLog(@"Updated with diff: %@", diff);
    NSLog(@"Total: %ld", (long)_collection.count);

This quickly clutters the console output, which should IMHO contain errors and warnings only. My guess is that this is a leftover from development and could be removed.

**Comment by morganchen12** [comment]
Fixed in 4.5.3.

**Comment by ghowen** [comment]
Still getting it with the 4.5.4 pod although it seems to be removed from code. Maybe it didn't make it in the pod?

**Comment by morganchen12** [comment]
This should be fixed for real this time in 4.5.5.
