### ISSUE TITLE
No display name for users signed up by email in Firebase Auth

### ISSUE THREAD

**Issue by Johnson145** [firebase/FirebaseUI-iOS#725]
### My environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.3.0
  * Firebase Component: Auth
  * Component version: 6.1.2

### Problem description
I'm using the pre-built UI of Firebase Auth. When a user signs up by email, the UI lets him/her enter the user name (label asks for the first and last name combined as one input). However, I can't see a way to get that information later on. Instead, the `firebaseUser.displayName` is nil for those users. That's not the way it's meant to be, is it?

**Comment by morganchen12** [comment]
Are there any errors in console when signing in? Can you see those users' names in Firebase console?

**Comment by Johnson145** [comment]
Thanks for your quick reply!

I don't get any error message. Everything else is working just fine: the user is logged in and I can access other information like the email address.

I can see the user along with e.g. the email address in the Firebase console, too. However, the Firebase console does not show the (display) name of any user in the first place, does it?

**Comment by morganchen12** [comment]
Good point, it doesn't. Can you see the display name in the user's provider info? Also, what version of FirebaseUI are you using?

**Comment by Johnson145** [comment]
No, the provider info does not provide that name either. It does contain only the providerID ("password"), the email and the userID which equals the email. The rest is nil.

I'm including the following FirebaseUI pods:
```
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Email'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Facebook'
pod 'FirebaseUI/Phone'
```
All of them using the latest version 8.0.2.

**Comment by morganchen12** [comment]
Sounds like a bug. We'll investigate.

**Comment by Johnson145** [comment]
Just found this issue: #262. Looks like my issue is a duplicate of the former one. The bug still seems to exist though. 

Furthermore, I can confirm that `firebaseUser.displayName` seems to get updated later on. I managed to get the correct value in the `didSignInWith` callback. It's still not in sync with the provider data though. The latter does still contain the old displayName instead of the one provided when signing up by email. In each case, all of these values should get updated before triggering any callback in the first place, right?

**Comment by andynovak12** [comment]
@morganchen12 I am also experiencing this issue. Is there an ETA of when this will be resolved?

**Comment by morganchen12** [comment]
Hey, unfortunately I haven't had time to make significant contributions to this SDK in a while. We're in the middle of some reshuffling that will hopefully get us some more contributors to FirebaseUI, but between the reporting of this bug and now there hasn't been any progress made.

Sorry for the delays.

**Comment by VedankPande** [comment]
I've been getting the same problem, any updates from Google/Firebase?

**Comment by SharpBCD** [comment]
Problem is still there. Any updates?
The name is required in the interface for creating a user but it is not available when getting the user back in admin

**Comment by yuchenshi** [comment]
@rosalyntan Would you mind taking a look at this one?

**Comment by morganchen12** [comment]
This should be fixed in the latest version of FirebaseUI. Please let me know if that's not the case.

**Comment by romrell4** [comment]
I'm still seeing the error in FirebaseUI 12 @morganchen12 :( After logging in with using the email provider, the displayName is nil. If I log out and back in, it is then set to the correct value from the UI

**Comment by AntonOliinyk-TomTom** [comment]
Have the same issue with the Apple id login.  When I call Auth.auth().signIn(with: credentials) I got the result, but user.displayName is always nil. If I use auth with Google credentials it works just fine.

**Comment by alsiesta** [comment]
Have the same issue. Funny though, that when using connectAuthEmulator the locally emulated console does show the displayName and it can be easily edited.

**Comment by cmederos** [comment]
Still an issue at the end of 2023. Especially annoying considering the `FIRAuthStateDidChangeListenerHandle` does not include profile updates, nor is there an equivalent listener.

I've only been able to work around this by placing a delay in the the body of the auth listener if the display name is empty. 

However, the complexity around the listener, delay, and rendering the UI accordingly is greater than the complexity avoided by using the prebuilt UI. We could use a better solution here...
- a change in the firebase code to await the profile update when performing a user creation with an email provider?
- a method in the SDK to request the user details from the firebase backend?
- at least a mention in the docs that this async issue exists?
- removing the name field from the prebuilt form so that we can add it in our apps ourselves?

**Comment by morganchen12** [comment]
@cmederos the issue you're describing sounds like it originates in the upstream [Firebase SDK](https://github.com/firebase/firebase-ios-sdk). Please file a new issue there instead.
