### ISSUE TITLE
Facebook Authentication button has no action in iOS 13.2.2

### ISSUE THREAD

**Issue by SAPIENTechnologies** [firebase/FirebaseUI-iOS#800]
### Step 2: Describe your environment

  * Swift 5.1
  * iOS version: 13.2.2
  * Firebase SDK version: 4.44.1
  * FirebaseUI version: 6.2.1
  * CocoaPods Version: 1.8.3
  
### Step 3: Describe the problem:
Have been using FirebaseUI in my project for several iterations. This includes Google, Facebook and email authentication. Using the same build on iOS 13.2.2 and on iOS 12.4.1. On 12.4.1 I can tap on the Facebook button and properly authenticate using Facebook. On 13.2.2 nothing happens when I tap on Facebook button. No error, no output to debug console, not a single thing. Google and email buttons work as expected.

#### Steps to reproduce:

  1. Install firebaseUI as instructed on Firebase UI instruction page
  2. Setup Facebook, Google and email authentication
  3. Run app on iOS 13.2.2 and tap on Facebook Button. Nothing happens
  
#### Observed Results:

  Nothing. Ne error, now activity, no output on debug console
  
#### Expected Results:

  *expect the app to start process of Logging in with facebook.

**Comment by flashadvanced** [comment]
I have the same issue.

FirebaseUI version: 7.0.0
iOS version: 13.1.3

**Comment by flashadvanced** [comment]
Hey, any news about this one? It is blocking my users from registering / logging in into my live app. At least is there any workaround I can apply for a quick fix?

**Comment by flashadvanced** [comment]
What I tried is adding a FBLoginButton programmatically just to test if it would work but again it doesn't work on iOS 13. You probably saw what XCode prints out when testing on simulator but still:
`-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"`

**Comment by SAPIENTechnologies** [comment]
I have not seen any error messages at all.

**Comment by morganchen12** [comment]
Looks like that's [`kLSApplicationNotFoundErr`](https://www.osstatus.com/search/results?platform=all&framework=all&search=-10814), which either means you haven't installed the Facebook app on the target device or you're missing the `LSApplicationQueriesSchemes` defined in step 3 of [Facebook's documentation](https://developers.facebook.com/docs/ios/getting-started/).

**Comment by SAPIENTechnologies** [comment]
Thank you fro that response. I do have the Facebook app installed on the device. LSApplicationQueriesSchemes was missing but when I added it, it had no effect. I have a second project that shows the same problem and I will add it there to see if it helps.

**Comment by flashadvanced** [comment]
> Looks like that's [`kLSApplicationNotFoundErr`](https://www.osstatus.com/search/results?platform=all&framework=all&search=-10814), which either means you haven't installed the Facebook app on the target device or you're missing the `LSApplicationQueriesSchemes` defined in step 3 of [Facebook's documentation](https://developers.facebook.com/docs/ios/getting-started/).

Yeah, I have them all set up and nothing. It doesn't make sense as it's working on iOS 12. Do you think there might be a connection between both issues: https://github.com/facebook/facebook-ios-sdk/issues/1067?

**Comment by SAPIENTechnologies** [comment]
I have created a stripped down app that shows the problem. I have added a bunch of break points and when I step through those breakpoints I get the following output:

Connection Event: Remote host connection complete. Initiating SSL handshake.
Status code: 0
 Description: OK
Status code: 0
 Description: OK
SSHStatus: Sending local version: "SSH-2.0-IPWorks SSH Client 2020".

SSHStatus: Read remote version string: "SSH-2.0-OpenSSH_for_Windows_7.7".

SSHStatus: Beginning key exchange

SSHStatus: Preparing algorithm negotiation.

SSHStatus: Sending local enabled algorithm list.

SSHStatus: Local Key Exchange Algorithms: 
    Key exchange algorithms: 
        curve25519-sha256,
        curve25519-sha256@libssh.org <mailto:curve25519-sha256@libssh.org> ,
        diffie-hellman-group14-sha1,
        diffie-hellman-group14-sha256,
        diffie-hellman-group1-sha1,
        diffie-hellman-group-exchange-sha256,
        diffie-hellman-group-exchange-sha1,
        diffie-hellman-group16-sha512,
        diffie-hellman-group18-sha512,
        ecdh-sha2-nistp256,
        ecdh-sha2-nistp384,
        ecdh-sha2-nistp521
    Server host key algorithms: 
        ssh-ed25519,
        ecdsa-sha2-nistp256,
        ecdsa-sha2-nistp384,
        ecdsa-sha2-nistp521,
        ssh-rsa,
        ssh-dss,
        x509v3-sign-rsa,
        x509v3-sign-dss
    Encryption algorithms: 
        aes256-ctr,
        aes192-ctr,
        aes128-ctr,
        aes256-cbc,
        aes192-cbc,
        aes128-cbc,
        3des-ctr,
        3des-cbc,
        blowfish-cbc,
        arcfour256,
        arcfour128,
        arcfour,
        cast128-cbc,
        aes256-gcm@openssh.com <mailto:aes256-gcm@openssh.com> ,
        aes128-gcm@openssh.com <mailto:aes128-gcm@openssh.com> ,
        chacha20-poly1305@openssh.com <mailto:chacha20-poly1305@openssh.com> 
    MAC algorithms: 
        hmac-sha2-256,
        hmac-sha2-512,
        hmac-sha1,
        hmac-md5,
        hmac-ripemd160,
        hmac-sha1-96,
        hmac-md5-96,
        hmac-sha2-256-96,
        hmac-sha2-512-96,
        hmac-ripemd160-96,
        hmac-sha2-256-etm@openssh.com <mailto:hmac-sha2-256-etm@openssh.com> ,
        hmac-sha2-512-etm@openssh.com <mailto:hmac-sha2-512-etm@openssh.com> 
    Compression algorithms: 
        none,
        zlib

SSHStatus: Reading remote enabled algorithm list.

SSHStatus: Remote Key Exchange Algorithms: 
    Key exchange algorithms: 
        curve25519-sha256,
        curve25519-sha256@libssh.org <mailto:curve25519-sha256@libssh.org> ,
        ecdh-sha2-nistp256,
        ecdh-sha2-nistp384,
        ecdh-sha2-nistp521,
        diffie-hellman-group-exchange-sha256,
        diffie-hellman-group16-sha512,
        diffie-hellman-group18-sha512,
        diffie-hellman-group14-sha256,
        diffie-hellman-group14-sha1
    Server host key algorithms: 
        ssh-rsa,
        rsa-sha2-512,
        rsa-sha2-256,
        ecdsa-sha2-nistp256,
        ssh-ed25519
    Encryption algorithms: 
        chacha20-poly1305@openssh.com <mailto:chacha20-poly1305@openssh.com> ,
        aes128-ctr,
        aes192-ctr,
        aes256-ctr,
        aes128-gcm@openssh.com <mailto:aes128-gcm@openssh.com> ,
        aes256-gcm@openssh.com <mailto:aes256-gcm@openssh.com> 
    MAC algorithms: 
        umac-64-etm@openssh.com <mailto:umac-64-etm@openssh.com> ,
        umac-128-etm@openssh.com <mailto:umac-128-etm@openssh.com> ,
        hmac-sha2-256-etm@openssh.com <mailto:hmac-sha2-256-etm@openssh.com> ,
        hmac-sha2-512-etm@openssh.com <mailto:hmac-sha2-512-etm@openssh.com> ,
        hmac-sha1-etm@openssh.com <mailto:hmac-sha1-etm@openssh.com> ,
        umac-64@openssh.com <mailto:umac-64@openssh.com> ,
        umac-128@openssh.com <mailto:umac-128@openssh.com> ,
        hmac-sha2-256,
        hmac-sha2-512,
        hmac-sha1
    Compression algorithms: 
        none

SSHStatus: Selected key exchange algorithm: "curve25519-sha256".

SSHStatus: Selected server host key algorithm: "ssh-ed25519".

SSHStatus: Selected client encryption algorithm: "aes256-ctr".

SSHStatus: Selected server encryption algorithm: "aes256-ctr".

SSHStatus: Selected client MAC algorithm: "hmac-sha2-256".

SSHStatus: Selected server MAC algorithm: "hmac-sha2-256".

SSHStatus: Selected client compression algorithm: "none".

SSHStatus: Selected server compression algorithm: "none".

SSHStatus: Algorithm negotiation complete.

SSHStatus: Sending ECDH key exchange initialization request.



I get a crash after the last line above.

Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

I will zip up and send the test app when I have finished cleaning it up.


Regards,
info@sapien.com <mailto:info@sapien.com> 



On Nov 14, 2019, at 9:48 AM, Morgan Chen <notifications@github.com <mailto:notifications@github.com> > wrote:

Looks like that's kLSApplicationNotFoundErr, which either means you haven't installed the Facebook app on the target device or you're missing the LSApplicationQueriesSchemes defined in step 3 of Facebook's documentation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

<http://schema.org>

**Comment by morganchen12** [comment]
@SAPIENTechnologies If you can share the stack trace of the crash that would also be helpful. It looks like it's a different issue than the one @flashadvanced is describing.

To clarify if it's a FirebaseUI issue, are you able to sign into Facebook _without_ using the Firebase SDK?

**Comment by SAPIENTechnologies** [comment]
Sorry. I posted that to the wrong location. That is another problem that is unrelated.

**Comment by flashadvanced** [comment]
> To clarify if it's a FirebaseUI issue, are you able to sign into Facebook _without_ using the Firebase SDK?

Yeah, as I posted I tested with creating a Fb button (FBSDKLoginButton) programmatically and it behaved the same way as the fb button added automatically by FirebaseUI. So I guess this have to be a Facebook issue. I disabled the Fb login for now.

**Comment by morganchen12** [comment]
Thanks all, we'll keep this open to track the Facebook issue and then update our podspec when a fix is released.

In the meantime you can also try testing older versions of the `FBSDKLoginKit` framework to see if the issue isn't reproducible on an older version.

**Comment by softmastx** [comment]
Still broken
Real Device with iOS 12.3.2 = **OK**
iOS Simulator 13.3 = **Failed**

**Comment by sungjin0213** [comment]
What Facebook SDK versions are you using? For me, same error was resolved when I updated Facebook SDK to 5.13.1. 

I was using Facebook SDK 5.4.0 version which worked fine until iOS 13, and I had to update SDK in order for facebook button to work again.

**Comment by jlandyr** [comment]
I've solved the same problem updating my pods FirebaseUI to the latest version:
```
pod 'FirebaseUI/Facebook', '~> 8.0'
pod 'FirebaseUI/Auth', '~> 8.0'
pod 'FirebaseUI/Email', '~> 8.0'
```
And also the next pod:
```
pod 'Firebase/Database', '~> 6.0'
```
to a version 6.0 or higher because:
FirebaseUI (~> 8.0) was resolved to 8.0.1, which depends on FirebaseUI/Database (= 8.0.1) was resolved to 8.0.1, which depends on Firebase/Database (~> 6.0)

**Comment by russellwheatley** [comment]
Hello,

Thank you for taking the time to submit this bug.

A new release is planned shortly for SwiftUI native Auth that replaces the previous Auth FirebaseUI, which should resolve this request. 

In the meantime, we will close this issue, if this is not resolved in the new version - please feel free to create a new issue.
