### ISSUE TITLE
Left-align apple button

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-iOS#888]
The sign in with apple button is currently centered and all others are left-aligned:
![image](https://user-images.githubusercontent.com/8466666/88842113-fbf5ee00-d1ac-11ea-8552-a01e76e3d541.png)

We should follow Apple's newly published guidance:
https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/

**Comment by samtstern** [comment]
Accidentally filed this issue on Android but it's an iOS issue.

**Comment by malcolmdeck** [comment]
I think @morganchen12 may know something about this - @renkelvin may have implemented something for this a while ago.

**Comment by wimzee-rcheng** [comment]
+1 on this issue

**Comment by morganchen12** [comment]
This should be fixed in the latest release.

**Comment by xaphod** [comment]
@morganchen12 This is still happening in latest version 13.1.0, please can you take another look

**Comment by russellwheatley** [comment]
Hello,

Thank you for taking the time to submit this bug.

A new release is planned shortly for SwiftUI native Auth that replaces the previous Auth FirebaseUI, which should resolve this request.

You can create completely custom Views which allow you to align auth buttons however you wish.

In the meantime, we will close this issue, if this is not resolved in the new version - please feel free to create a new issue.
